"""Utility modules for the Insight Generator Agent."""

from .prompts import (
    DATA_ANALYZER_INSTRUCTIONS,
    INSIGHT_GENERATOR_INSTRUCTIONS,
    ANALYSIS_REQUEST_TEMPLATE,
    QUICK_ANALYSIS_QUERIES,
)

__all__ = [
    "DATA_ANALYZER_INSTRUCTIONS",
    "INSIGHT_GENERATOR_INSTRUCTIONS",
    "ANALYSIS_REQUEST_TEMPLATE",
    "QUICK_ANALYSIS_QUERIES",
]
